baseURL = "https://biodati.com/"
languageCode = "en-us"
title = "BioDati, Inc."
theme = "terrassa.copy"
favicon = "favicon-32x32.png" # Relative URL
googleAnalytics = "UA-114538730-1"

[Params]
  author = ""
  image = ""
  description = ""

[[menu.header]]
identifier = "Our Platform"
name = "Our Platform"
url = "/platform/"
weight = 1

[[menu.header]]
identifier = "Platform Technology"
name = "Platform Technology"
url = "/platformtech/"
weight = 1

[[menu.header]]
identifier = "BioDati Demo"
name = "launch The Demo"
url = "/demo/"
weight = 2

[[menu.header]]
identifier = "explore"
name = "Resources"
url = ""
weight = 3

[[menu.header]]
parent = "explore"
identifier = "blog"
name = "Blogs"
url = "/blog/"
weight = 4

[[menu.header]]
parent = "explore"
identifier = "notes"
name = "Release Notes"
url = "/releaseNotes/"
weight = 5

[[menu.header]]
parent = "explore"
identifier = "faq"
name = "FAQ's"
url = "/faqs/"
weight = 6

[[menu.header]]
parent = "explore"
identifier = "presentations"
name = "Presentations"
url = "/presentations/"
weight = 7

[[menu.header]]
parent = "explore"
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 8

[[menu.header]]
parent = "explore"
identifier = "videos"
name = "Videos"
url = "/videos/"
weight = 9

[[menu.header]]
parent = "explore"
identifier = "webinars"
name = "Webinars"
url = "/webinars/"
weight = 10





[[menu.header]]
identifier = "AboutUs"
name = "About Us"
url = "/aboutus/"
weight = 11

[[menu.header]]
parent = "AboutUs"
identifier = "Our Team"
name = "Meet The Team"
url = "/aboutus/"
weight = 12

[[menu.header]]
parent = "AboutUs"
identifier = "events"
name = "Events"
url = "/careers/"
weight = 13

[[menu.header]]
parent = "AboutUs"
identifier = "news"
name = "News"
url = "/careers/"
weight = 14

[[menu.header]]
parent = "AboutUs"
identifier = "careers"
name = "Careers"
url = "/careers/"
weight = 15

[menu]
[[menu.header]]
identifier = "contact"
name = "Contact Us"
url = "#myModal"
weight = 16
[menu.header.params]
    class = "contact"

[[menu.footer]]
identifier = "cookies"
name = "Cookies Policy"
url = "/cookies/"
weight = 0

[[menu.footer]]
identifier = "policy"
name = "Privacy Policy"
url = "/policy/"
weight = 0

[[menu.footer]]
identifier = "adsworks"
name = "ADSWORKS"
url = "http://www.adsworks.com"
weight = 1
