baseURL = "https://biodati.com/"
languageCode = "en-us"
title = "BioDati, Inc."
theme = "terrassa.copy"
favicon = "favicon-32x32.png" # Relative URL
googleAnalytics = "UA-114538730-1"

[menu]
[[menu.header]]
identifier = "contact"
name = "Contact Us"
url = "mailto:help@biodati.com"
weight = 0

[[menu.header]]
identifier = "faq"
name = "FAQ's"
url = "/faqs/"
weight = 0

[[menu.header]]
identifier = "blog"
name = "Blog"
url = "https://medium.com/biodati"
weight = 0

[[menu.footer]]
identifier = "cookies"
name = "Cookies Policy"
url = "/cookies/"
weight = 0

[[menu.footer]]
identifier = "policy"
name = "Privacy Policy"
url = "/policy/"
weight = 0

[[menu.footer]]
identifier = "adsworks"
name = "ADSWORKS"
url = "http://www.adsworks.com"
weight = 1
