baseURL = "http://biodati.com/"
languageCode = "en-us"
title = "BioDati, Inc."
theme = "terrassa"

[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact Us"
    url = "mailto:help@biodati.com"
    weight = 0